---
title: ligi
description: this is ligi's landing page with links to github, .. 
relative_permalinks: false
markdown: kramdown
url: "http://ligi.de"

exclude:
  - app.coffee
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - Rakefile
  - README.md
  - script
  - vendor/bundle
  - test
  - tests
  - assets/vendor/selectivizr/tests
  - assets/vendor/clipboard/test

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

sass:
    sass_dir: _sass
    style: :compressed


